// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4j8-SPCbUmdFGtDrAdq1kxFk4LeBoQGI',
    appId: '1:656354073125:web:fe4b90216cdbde8486fdcc',
    messagingSenderId: '656354073125',
    projectId: 'la-fetch-3b250',
    authDomain: 'la-fetch-3b250.firebaseapp.com',
    storageBucket: 'la-fetch-3b250.appspot.com',
    measurementId: 'G-BR7YX5SDJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKveQDCOONBp6t6KOSrbg6fhoQWp8t-n0',
    appId: '1:656354073125:android:ba443aa700205a2286fdcc',
    messagingSenderId: '656354073125',
    projectId: 'la-fetch-3b250',
    storageBucket: 'la-fetch-3b250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRWXD2dx8llBpwxlulHntURgnwf0cE-jU',
    appId: '1:656354073125:ios:ff85960cf322344686fdcc',
    messagingSenderId: '656354073125',
    projectId: 'la-fetch-3b250',
    storageBucket: 'la-fetch-3b250.appspot.com',
    androidClientId: '656354073125-0l8dgbuisu2o8qefhgkov4avl71a19lu.apps.googleusercontent.com',
    iosClientId: '656354073125-7vht6l8p69chgg2il02c4pjv0r1okufb.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRWXD2dx8llBpwxlulHntURgnwf0cE-jU',
    appId: '1:656354073125:ios:ff85960cf322344686fdcc',
    messagingSenderId: '656354073125',
    projectId: 'la-fetch-3b250',
    storageBucket: 'la-fetch-3b250.appspot.com',
    androidClientId: '656354073125-0l8dgbuisu2o8qefhgkov4avl71a19lu.apps.googleusercontent.com',
    iosClientId: '656354073125-7vht6l8p69chgg2il02c4pjv0r1okufb.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4j8-SPCbUmdFGtDrAdq1kxFk4LeBoQGI',
    appId: '1:656354073125:web:a9341db18685768086fdcc',
    messagingSenderId: '656354073125',
    projectId: 'la-fetch-3b250',
    authDomain: 'la-fetch-3b250.firebaseapp.com',
    storageBucket: 'la-fetch-3b250.appspot.com',
    measurementId: 'G-695V7YQ1V4',
  );
}
